/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://oqkesf5grvcovj6ac27lza3xvq.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lquxyua44fgxnkstkjshws2q3m",
    "aws_cognito_identity_pool_id": "ap-southeast-1:52fb866c-db87-4775-97ef-dbaed6487fe2",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_t1cGtY1i7",
    "aws_user_pools_web_client_id": "76mp3bij1naigbj2h7gif26j75",
    "oauth": {
        "domain": "designerfrontendb1a541a0-b1a541a0-dev.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://main.dqw0ncfsshc.amplifyapp.com/,https://kannan-dev.dqw0ncfsshc.amplifyapp.com/,https://kannan-dev.dqw0ncfsshc.amplifyapp.com/",
        "redirectSignOut": "http://localhost:3000/,https://main.dqw0ncfsshc.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "designer-s3-bucket-51755381897551cca-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};


export default awsmobile;
